---

- name: Clone dotvim directory
  git:
    repo: git@github.com:lukeorland/dotvim.git
    dest: "{{ user_home }}/.vim"
    version: master
    accept_hostkey: yes
  notify:
    - install vim plugins

- name: Create .vimrc and .gvimrc symlinks
  file:
    src: "{{ user_home }}/{{ item }}"
    dest: "{{ user_home }}/.{{ item }}"
    force: yes
  with_items:
    - vimrc
    - gvimrc
