---
# https://github.com/robbyrussell/oh-my-zsh#the-manual-way

- name: Install zsh
  apt:
    name: zsh
  sudo: yes
  when: ansible_os_family == "Debian"

- name: Clone oh-my-zsh
  git:
    repo: "git://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ user_home }}/.oh-my-zsh"
    version: master

- name: ~/.zshrc
  file:
    path: "{{ user_home }}/.zshrc"
    src: "{{ user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    state: link
    force: yes

- name: Set Zsh as default shell (OS X)
  shell: chsh -s `which zsh` {{ user_name }}
  sudo: yes
  register: chsh
  changed_when: '"chsh: no changes made" not in chsh.stderr'
  when: ansible_os_family == "Darwin"

- name: Zsh theme
  lineinfile:
    line: 'ZSH_THEME="steeef"'
    dest: "{{ user_home }}/.oh-my-zsh/custom/theme.zsh"
    create: yes
