---

- name: Clone dotvim directory
  git:
    repo: git@github.com:lukeorland/dotvim.git
    dest: "{{ user_home }}/.vim"
    version: master
    accept_hostkey: yes
  notify:
    - install vim plugins
